# 사이트 정보
title: "1도 몰라서 쓰는 " # 블로그 제목
description: "언제 1을 쓰고 2를 쓸까" # 블로그 설명
url: "https://marideev.github.io"  # GitHub Pages 주소
baseurl: ""  # 루트라면 "" 비워두기

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# 작성자 정보 (선택)
author:
  name: "marius"
  email: "hong@example.com"

# 사이드바 구성
just_the_docs:
  collections:
    docs:
      name: Documentation
      permalink: /:collection/:path/
      output: true

# 마크다운 엔진 설정
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown

# 포스트 설정
permalink: /:year/:month/:day/:title/
timezone: Asia/Seoul

# 폴더 설정
collections:
  posts:
    output: true


# 플러그인 (GitHub Pages에서 지원되는 것만)
plugins:
  - jekyll-feed        # RSS 피드
  - jekyll-seo-tag     # SEO 자동 메타태그
  - jekyll-sitemap     # sitemap.xml 생성

# Build 제외 설정 (선택)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# 기타
show_excerpts: true
